export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>DASH BOARD</h1>
        <a href="/dashboard/login">login</a>
        {children}
      </body>
    </html>
  );
}
