import Navigator from "../components/auth/navigator.server";
// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body>
        <h1>
          <a href="/">DASH BOARD</a>
        </h1>
        <div>
          <Navigator />
        </div>
        {children}
      </body>
    </html>
  );
}
